### ISSUE TITLE
Compile only certain contracts

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/etherlime#150]
Use case:
I have several contracts in my project. Some of them are already deployed and used in production.

```
Project
└───contracts
│   └───old-contracts
│   |    contract-1-v-0.2.4.sol
│   |    contract-2-v-0.2.4.sol
│   └───new-contracts
│        contract-1-v-0.5.1.sol
│        contract-2-v-0.5.1.sol
│   
└───deployment
    │   deploy.js
|
└───test
```

Currently there is no way I can specify only the `old-contracts` to be compiled.

It would be nice to have a feature so that I can specify a certain contract that I want to compile. Compiling whole folder folder would be nice to. 

for e.g:
```
etherlime compile old-contracts --solcVersion=0.2.4

etherlime compile old-contracts/contract-1-v-0.2.4.sol --solcVersion=0.2.4

etherlime compile new-contracts --solcVersion=0.5.1

```

**Comment by ochikov** [comment]
This issue is already fixed. You can use these both optional params:

```buildDirectory``` - [Optional] Defines the directory for placing builded contracts.
```workingDirectory``` - [Optional] Defines the folder to use for reading contracts from, instead of the default one: ```./contracts```. Here can be specified also a single solidity file for compiling e.g: ```/contracts/LimeFactory.sol.```
