### ISSUE TITLE
Add HD wallet derivation to Etherlime Ganache

### ISSUE THREAD

**Issue by amiromayer** [LimeChain/etherlime#184]
We certainly need more than 10 accounts for 🍋 Etherlime Ganache. 
Currently Etherlime Ganache has all the wallets hardcoded in a JSON file. 
We need to derive them from mnemonic phrase using HD wallet as described [here](https://docs.ethers.io/ethers.js/html/api-wallet.html)

This way we will be able to derive as many accounts as we want. 

Consider also adding a CLI option like etherlime `etherlime ganache --generate 25` to derive 25 different pre-funded accounts. 

And an option to set the mnemonic phrase `etherlime ganache --mnemonic "radar blur cabbage chef fix engine embark joy scheme fiction master release"`, so that using the same mnemonic, we will always be able to derive the same addresses.

**Comment by BenSchZA** [comment]
I think that's a great idea. When I eventually get around to cleaning up the Ganache alternative feature branch, this would be a useful feature there too: https://github.com/LimeChain/etherlime/pull/154 .

**Comment by NikolayAngelov** [comment]
Hello guys.
Actually, I think that there is a better approach then touching the `Ganache`.

My idea is that instead of changing the current `Ganache` functionality to actually make the proposed `--generate` command to just write the new accounts needed to the `setup.json` and then just continue executing the normal way.
Besides that, we can have an `etherlime ganache load mnemonic` which will do the same. It will go and load the accounts from the mnemonic into the `setup.json` and continue as normal.

I think this is better for a few reasons.

- We don't touch anything that we currently have.

- By writing into `setup.json` after requiring more accounts we remove the need to to do `generate amount` every single time we reset the `ganache` and after each reset you will be able to just do `etherlime ganache` and it will spawn the same 25 accounts (from the example)

- In case you need to be loading from `mnemonic` again you won't need to be doing it all the time. You will do it once it will be stored in the fail and you will have your setup.

In case the team is happy with that I think I can get it done by the end of the week.

**Comment by amiromayer** [comment]
Hi, Nikolay. Why not consider `etherlime ganache --mnemonic "radar blur cabbage chef fix engine embark joy scheme fiction master release" --generate 25` which will write 25 accounts derived from mnemonic to `setup.json` so that we can then use `etherlime ganache` as usual without needing to `generate` every single time?

**Comment by NikolayAngelov** [comment]
That is exactly what I said :)

**Comment by amiromayer** [comment]
Sorry, might have misunderstood some parts 😄. 
Anyway, cool then, I like this approach.

**Comment by amiromayer** [comment]
Hi there, any update on this issue?

**Comment by ochikov** [comment]
This issue is now resolved. We have implemented the desired optional parameters for ```etherlime ganache``` command. Please refer to: https://etherlime.readthedocs.io/en/latest/cli/ganache.html
