### ISSUE TITLE
how to get contract balance

### ISSUE THREAD

**Issue by javaadpatel** [LimeChain/etherlime#232]
Hi, might have missed this in the docs, how do i get the balance of a contract after assiging an instance using:
`const investmentInstance = await etherlime.ContractAt(Investment, contractAddress);`

also, is:
`await investmentInstance.invest({value: initialInvestmentWei});` the correct way to send money into a contract using etherlime

**Comment by Perseverance** [comment]
Hey @javaadpatel , in order to avoid conflicting methods we've not added "checkBalance" or "send" function directly in the contract instance. Here is how you can do the two things you want with ethers ( I will make sure to add them in the docs, and maybe add them in a special "utils" field of the contract instance in the future.

### Sending money with contract function invocation
If you want to add value while calling a function of your contract your example is correct.

### Sending Money to the fallback function
If you just want to send eth to address (to its fallback function), best way is to use the sendTransaction method of the wallet instance.

```
const investmentWallet = investmentInstance.signer; // or account[5].signer works too, or any other ethers wallet instance

const tx = await investmentWallet.sendTransaction({ to: investmentInstance.contractAddress, value: 500000 });
await investmentInstance.verboseWaitForTransaction(tx);
```

### Checking the balance of an address
Best way is just to use the provider of the contract you are using for that
```
	const balance = await investmentInstance.provider.getBalance(investmentInstance.contractAddress);
	console.log(balance.toString())
```

**Comment by javaadpatel** [comment]
that worked perfectly, thanks so much.
