### ISSUE TITLE
[Feature Request] Devnet intergration as Ganache alternative

### ISSUE THREAD

**Issue by RyRy79261** [LimeChain/etherlime#240]
## Context

We've had multiple issues with Ganache where transactions are reverted on Ganache, yet succeed in Remix with the JavaScript VM. This has rendered the standard Etherlime packages unusable to us.

## References
[Our fork](https://github.com/BenSchZA/etherlime/tree/temp-feature)
[Devnet testnet](https://github.com/0xProject/0x-monorepo/tree/development/packages/devnet)
[Pending PR](https://github.com/LimeChain/etherlime/pull/154 )

**Comment by Perseverance** [comment]
Hey @RyRy79261 upon investigation it seems that devnet is no longer maintained. I made an effort to make it work, but due to ethers version working with constantinople and post-constantinople EVM versions, I could not make the devnet work. At this point I am not sure if it makes sense to integrate it as the 0x team has said that they will not maintain it and the current version will only work for portion of the etherlime users.
https://github.com/0xProject/0x-monorepo/issues/1831#issuecomment-495340127

**Comment by RyRy79261** [comment]
Thanks @Perseverance, I'll investigate alternatives with @BenSchZA next week and revert back
