### ISSUE TITLE
Etherlime coverage does not work with ganache provider

### ISSUE THREAD

**Issue by kenchangh** [LimeChain/etherlime#269]
In my tests, I am using a `ganache-core` provider, that is attached to the `EtherlimeGanacheDeployer`. This is so that when I run the tests, I do not have to run `etherlime ganache` which opens a port and it is invoked directly in the script.

See the screenshot below on how it's done:

![Screenshot 2019-08-03 19 57 51](https://user-images.githubusercontent.com/5748750/62411654-04aef500-b629-11e9-915e-6b5bea1181ed.png)

The `etherlime test` works fine, however the `etherlime coverage` is not able to detect that the tests are run. Screenshot below:

<img width="537" alt="Screenshot 2019-08-02 16 36 12" src="https://user-images.githubusercontent.com/5748750/62411667-4fc90800-b629-11e9-8d64-cea51d524347.png">

**Comment by ochikov** [comment]
Thank you for the provided issue. Can you post a repository, where we can test ?

**Comment by ochikov** [comment]
@kenchangh I tried your implementation but I am getting connection error which makes me thing that we need a ganache running as a server and a port that we can listen on, because the coverage is collecting traces after each call.
I will continue researching it.

**Comment by ochikov** [comment]
I don't think that this is possible at this moment because for the purpose of the coverage we use `web3-provider-engine` library and add two providers - one for deployment and one for debugging (used for coverage). When in your code you call `setProvider` you overwrite the provider. I tried to add the provider which comes from ganache to the `web3-provider-engine` instance provider, but they do not support it yet. I will still continue to research and looking for solution.
